name: Manual
on:
  workflow_dispatch:

  push:
    branches:
      - main
      - develop

# env:
#   branch: ${{ github.event.workflow_run.head_branch }}

jobs:
  deploy:
    name: Maual
    runs-on: ubuntu-latest

    environment:  ${{ github.event.workflow_run.head_branch }}
    permissions:
      id-token: write
      contents: write
    
    if: github.ref == 'refs/heads/develop' || github.event_name == 'push'

    steps:
      - name: Print Branch Name
        run: echo ${{ github.ref_name }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print File
        run: |
          cat sample.txt
          git branch