name: Manual
on:
  workflow_dispatch:

  workflow_run:
    workflows: ["First"]  # Nombre del workflow previo
    types:
      - completed

  # push:
  #   branches:
  #     - main
  #     - develop

env:
  branch: ${{ github.event.workflow_run.head_branch }}

jobs:
  deploy:
    name: Maual
    runs-on: ubuntu-latest

    environment:  ${{ github.event.workflow_run.head_branch }}
    permissions:
      id-token: write
      contents: write
    
    env:
      branch: ${{ github.event.workflow_run.head_branch }}

    # if: ${{ branch }} == 'develop' || github.event_name == 'push'

    steps:
      - name: Determine branch
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch"]; then
            echo "branch=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
          fi

      - name: Print Branch Name
        run: echo ${{ github.ref_name }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print File
        run: |
          cat sample.txt
          git branch