name: Manual
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Maual
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Print Branch Name
        run: echo ${{ github.ref_name }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Print File
        run: |
          cat sample.txt
          echo git branch