name: Manual
on:
  workflow_dispatch:

  workflow_run:
    workflows: ["First"]  # Nombre del workflow previo
    types:
      - completed

  # push:
  #   branches:
  #     - main
  #     - develop

# env:
#   branch: ${{ github.event.workflow_run.head_branch }}

jobs:
  deploy:
    name: Maual
    runs-on: ubuntu-latest
    # environment:  ${{ github.event.workflow_run.head_branch }}
    permissions:
      id-token: write
      contents: write
    
    env:
      branch: ${{ github.ref_name }}

    # if: ${{ branch }} == 'develop' || github.event_name == 'push'

    steps:
      - name: Determine branch
        id: get_branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "branch=${{github.event.workflow_run.head_branch}}" >> $GITHUB_ENV
          fi

      - name: Print Branch Name
        run: echo ${{ env.branch }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}

      - name: Print File
        run: |
          cat sample.txt
          git branch
      
      - name: Set environment
        run: |
          echo "ENVIRONMENT= ${{ env.branch }}" >> $GITHUB_ENV
          
      - name: Print Environment
        run: echo ${{ vars.test_var }}
          